// Level setup configurations and validation logic
// This file contains the helper functions for Code Dojo level management

export const getLevelSetup = (levelId: number): string => {
    const setupMap: Record<number, string> = {
        2: "player = ''",
        3: "score = 10",
        4: "a=0\nb=0\ntotal=0",
        5: "x=1\ny=2",
        6: "x=0\ny=0\nresult=0",
        7: "width=0\nheight=0\narea=0",
        8: "total=0\nparts=0\neach=0",
        9: "first=''\nsecond=''\nmessage=''",
        10: "count=0",
        11: "num=0",
        12: "a=0\nb=0\nc=0\nsum=0",
        13: "x=0\ny=0\navg=0",
        14: "num=0\ndiv=0\nrem=0",
        15: "base=0\nexp=0\npower=0",
        16: "positive=0\nnegative=0",
        17: "num=0\nabs=0",
        18: "decimal=0\nrounded=0",
        19: "a=0\nb=0\nmax=0",
        20: "x=0\ny=0\nresult=0",
        // Conditions (21-40)
        21: "password='1234'\naccess=False",
        22: "coin='heads'\nresult=''",
        23: "light='red'\naction=''",
        24: "score=51\nmedal=''",
        25: "day='Saturday'\nweekend=False",
        26: "age=18\nadult=False",
        27: "temp=25\ncomfortable=False",
        28: "num=4\ntype=''",
        29: "value=5\nsign=''",
        30: "score=90\ngrade=''",
        31: "user='admin'\npass='secret'\nlogged=False",
        32: "amount=101\ndiscount=0",
        33: "a=5\nb=12\nc=8\nmax=0",
        34: "year=2024\nleap=False",
        35: "a=5\nb=5\nc=5\ntype=''",
        36: "age=18\ncitizen=True\ncanVote=False",
        37: "temp=-5\nalert=''",
        38: "length=8\nstrong=False",
        39: "bmi=18\ncategory=''",
        40: "role='admin'\naccess=''",
        // Loops (41-60)
        41: "count=0",
        43: "n=10",
        44: "total=0",
        46: "i=0",
        47: "sum=0",
        48: "product=1",
        49: "n=0",
        50: "fact=1\ni=1",
        51: "total=0",
        52: "x=1",
        53: "count=0",
        54: "x=1",
        55: "product=1",
        56: "total=0",
        57: "result=1",
        58: "sum=0\ni=1",
        59: "a=0\nb=1\ntemp=0",
        60: "grand=0",
    };
    return setupMap[levelId] || "";
};

export const getLevelVariables = (levelId: number): string[] => {
    const varMap: Record<number, string[]> = {
        1: ['score'],
        2: ['player'],
        3: ['score'],
        4: ['a', 'b', 'total'],
        5: ['x', 'y'],
        6: ['x', 'y', 'result'],
        7: ['width', 'height', 'area'],
        8: ['total', 'parts', 'each'],
        9: ['first', 'second', 'message'],
        10: ['count'],
        11: ['num'],
        12: ['a', 'b', 'c', 'sum'],
        13: ['x', 'y', 'avg'],
        14: ['num', 'div', 'rem'],
        15: ['base', 'exp', 'power'],
        16: ['positive', 'negative'],
        17: ['num', 'abs'],
        18: ['decimal', 'rounded'],
        19: ['a', 'b', 'max'],
        20: ['x', 'y', 'result'],
        21: ['password', 'access'],
        22: ['coin', 'result'],
        23: ['light', 'action'],
        24: ['score', 'medal'],
        25: ['day', 'weekend'],
        26: ['age', 'adult'],
        27: ['temp', 'comfortable'],
        28: ['num', 'type'],
        29: ['value', 'sign'],
        30: ['score', 'grade'],
        31: ['user', 'pass', 'logged'],
        32: ['amount', 'discount'],
        33: ['a', 'b', 'c', 'max'],
        34: ['year', 'leap'],
        35: ['a', 'b', 'c', 'type'],
        36: ['age', 'citizen', 'canVote'],
        37: ['temp', 'alert'],
        38: ['length', 'strong'],
        39: ['bmi', 'category'],
        40: ['role', 'access'],
        41: ['count'],
        42: ['unlocked', 'try'],
        43: ['n'],
        44: ['item', 'total'],
        45: ['cheer'],
        46: ['i'],
        47: ['num', 'sum'],
        48: ['product'],
        49: ['n'],
        50: ['fact', 'i'],
        51: ['num', 'total'],
        52: ['x'],
        53: ['count'],
        54: ['x'],
        55: ['num', 'product'],
        56: ['total'],
        57: ['result'],
        58: ['sum', 'i'],
        59: ['a', 'b', 'temp'],
        60: ['val', 'grand'],
    };
    return varMap[levelId] || [];
};
