
import { Level, TileType } from './types';

export const GRID_SIZE = 8;


export const LEVELS: Level[] = [
  // --- PYQUEST: GRID CHALLENGES ---
  {
    id: 1,
    type: 'GRID',
    title: "First Steps",
    description: "Systems Active. Move Byte to the charging pad.",
    instruction: "Use `robot.move_forward()` to reach the goal.",
    concepts: ["Functions", "Movement"],
    startPos: { x: 1, y: 4 },
    goalPos: { x: 4, y: 4 },
    initialCode: "robot.move_forward()\nrobot.move_forward()\nrobot.move_forward()",
    grid: Array(8).fill(null).map((_, y) => 
      Array(8).fill(null).map((_, x) => (x === 4 && y === 4 ? TileType.GOAL : TileType.EMPTY))
    )
  },
  {
    id: 2,
    type: 'GRID',
    title: "Space Debris",
    description: "Obstacle detected. Navigate around it.",
    instruction: "Turn and move to avoid the wall.",
    concepts: ["Turning", "Sequencing"],
    startPos: { x: 1, y: 6 },
    goalPos: { x: 1, y: 2 },
    initialCode: "robot.move_forward()\nrobot.turn_right()\nrobot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 3,
    type: 'GRID',
    title: "The Long Bridge",
    description: "Crossing the void. Repetition is key.",
    instruction: "Use a `for` loop to cross the bridge.",
    concepts: ["For Loops"],
    startPos: { x: 0, y: 3 },
    goalPos: { x: 7, y: 3 },
    initialCode: "for i in range(7):\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 4,
    type: 'GRID',
    title: "Spiral Pattern",
    description: "A repeating spiral pattern into the core.",
    instruction: "Use nested loops or just repeat a pattern of move & turn.",
    concepts: ["Patterns", "Loops"],
    startPos: { x: 0, y: 0 },
    goalPos: { x: 4, y: 3 },
    initialCode: "for i in range(4):\n  robot.move_forward()\n  robot.turn_right()\n  robot.move_forward()\n  robot.turn_left()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 5,
    type: 'GRID',
    title: "Crystal Labyrinth",
    description: "The crystals interfere with our sensors. You'll need a precise loop of 8 steps.",
    instruction: "The goal is hidden behind a double-corner. Use loops and variables together.",
    concepts: ["Optimization", "Precision"],
    startPos: { x: 0, y: 0 },
    goalPos: { x: 2, y: 2 },
    initialCode: "for i in range(2):\n  robot.move_forward()\n  robot.move_forward()\n  robot.turn_right()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 6,
    type: 'GRID',
    title: "Galactic Mastery",
    description: "The final test! Reach the heart of the galaxy station using a loop and if-checks.",
    instruction: "Navigate the complex corridor. Move 10 times and check for walls at every step.",
    concepts: ["Mastery", "Final Exam"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 4, y: 4 },
    initialCode: "for i in range(12):\n  if robot.is_wall_ahead():\n    robot.turn_right()\n  robot.move_forward()",
    grid: [
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.GOAL, TileType.WALL, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 7,
    type: 'GRID',
    title: "Data Collection",
    description: "Collect data crystals (virtual) from the grid.",
    instruction: "Move to 3 different empty spots to simulate collection. (Just reach the goal for now!)",
    concepts: ["Movement", "Planning"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 6, y: 6 },
    initialCode: "robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 8,
    type: 'GRID',
    title: "Keep Moving",
    description: "Move until you hit a wall.",
    instruction: "Use `while not robot.is_wall_ahead():` to move.",
    concepts: ["While Loops", "Sensors"],
    startPos: { x: 1, y: 4 },
    goalPos: { x: 7, y: 4 },
    initialCode: "while not robot.is_wall_ahead():\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 9,
    type: 'GRID',
    title: "Patrol Route",
    description: "Patrol until energy runs out.",
    instruction: "Create a loop that moves forward, turns right, moves forward, turns left.",
    concepts: ["Complex Loops"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 5, y: 5 },
    initialCode: "while not robot.is_wall_ahead():\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 10,
    type: 'GRID',
    title: "Smart Move",
    description: "Create a custom move function.",
    instruction: "Define `move_twice()` and call it to reach the goal.",
    concepts: ["Functions", "Abstraction"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 5, y: 1 },
    initialCode: "def move_twice():\n  robot.move_forward()\n  robot.move_forward()\n\nmove_twice()\nmove_twice()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 11,
    type: 'GRID',
    title: "Turn Around",
    description: "It's efficient to have a turn_around function.",
    instruction: "Define `turn_around()` (2 turns). Use it to go back and forth.",
    concepts: ["Helper Functions"],
    startPos: { x: 2, y: 2 },
    goalPos: { x: 2, y: 2 }, // Return to start
    initialCode: "def turn_around():\n  robot.turn_left()\n  robot.turn_left()\n\nrobot.move_forward()\nturn_around()\nrobot.move_forward()\nturn_around()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 12,
    type: 'GRID',
    title: "Function Master",
    description: "Combine everything.",
    instruction: "Use a function to move N steps.",
    concepts: ["Advanced"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 6, y: 1 },
    initialCode: "def move_n(n):\n  for i in range(n):\n    robot.move_forward()\n\nmove_n(5)",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 13,
    type: 'GRID',
    title: "Mapped Path",
    description: "Follow the coordinates.",
    instruction: "A virtual dictionary says: move 2 then turn right. Execute it.",
    concepts: ["Logic"],
    startPos: { x: 0, y: 0 },
    goalPos: { x: 2, y: 1 },
    initialCode: "robot.move_forward()\nrobot.move_forward()\nrobot.turn_right()\nrobot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 14,
    type: 'GRID',
    title: "Object Guard",
    description: "The goal is guarded by an object.",
    instruction: "Just reach the goal using standard moves. (Conceptual link: Robots moving)",
    concepts: ["Movement"],
    startPos: { x: 0, y: 0 },
    goalPos: { x: 0, y: 4 },
    initialCode: "for i in range(4):\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 15,
    type: 'GRID',
    title: "Zig Zag",
    description: "Evasive maneuvers.",
    instruction: "Move in a zig-zag pattern to the goal.",
    concepts: ["Patterns"],
    startPos: { x: 0, y: 7 },
    goalPos: { x: 2, y: 3 },
    initialCode: "for i in range(2):\n  robot.move_forward()\n  robot.move_forward()\n  robot.turn_right()\n  robot.move_forward()\n  robot.turn_left()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 16,
    type: 'GRID',
    title: "The Gauntlet",
    description: "Navigate the asteroid field.",
    instruction: "A complex path requiring turns and moves.",
    concepts: ["Complex Path"],
    startPos: { x: 0, y: 0 },
    goalPos: { x: 7, y: 7 },
    initialCode: "while not (robot.x == 7 and robot.y == 7): # Pseudo code - just solve it!\n  robot.move_forward()\n  if robot.is_wall_ahead():\n    robot.turn_right()",
    grid: [
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.GOAL],
    ]
  },
  {
    id: 17,
    type: 'GRID',
    title: "Homecoming",
    description: "Return to base, Commander.",
    instruction: "A straight shot home. Enjoy the victory lap.",
    concepts: ["Victory"],
    startPos: { x: 0, y: 4 },
    goalPos: { x: 7, y: 4 },
    initialCode: "for i in range(7):\n  robot.move_forward()",
    grid: [
      [TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL], // Just for fun visuals
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL, TileType.GOAL],
    ]
  }
];
