
import { Level, TileType } from './types';

export const GRID_SIZE = 8;

export const LEVELS: Level[] = [
  {
    id: 1,
    title: "The First Step",
    description: "Welcome to Planet Py! Our robot, Byte, needs to reach the charging station.",
    instruction: "Use `robot.move_forward()` to reach the green goal. You need to move 3 spaces.",
    concepts: ["Functions", "Commands"],
    startPos: { x: 1, y: 4 },
    goalPos: { x: 4, y: 4 },
    initialCode: "robot.move_forward()\nrobot.move_forward()\nrobot.move_forward()",
    grid: Array(8).fill(null).map((_, y) => 
      Array(8).fill(null).map((_, x) => (x === 4 && y === 4 ? TileType.GOAL : TileType.EMPTY))
    )
  },
  {
    id: 2,
    title: "Navigating the Crater",
    description: "Oops! There's a wall in the way. Byte needs to turn.",
    instruction: "Use `robot.turn_left()` or `robot.turn_right()` to navigate around walls.",
    concepts: ["Navigation", "Turns"],
    startPos: { x: 1, y: 6 },
    goalPos: { x: 1, y: 2 },
    initialCode: "robot.move_forward()\nrobot.turn_right()\nrobot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 3,
    title: "The Power of Repetition",
    description: "Byte needs to travel across a long bridge. Writing 7 moves is tiring!",
    instruction: "Use a `for` loop to repeat actions. Syntax: `for i in range(7):`",
    concepts: ["For Loops", "Indentation"],
    startPos: { x: 0, y: 3 },
    goalPos: { x: 7, y: 3 },
    initialCode: "for i in range(7):\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 4,
    title: "Energy Storage",
    description: "Variables help us remember numbers. Store the distance in a variable called 'steps'.",
    instruction: "Try `steps = 5` and then `for i in range(steps):`",
    concepts: ["Variables", "Dynamic Loops"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 1, y: 6 },
    initialCode: "steps = 5\nfor i in range(steps):\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 5,
    title: "Zig-Zag Trail",
    description: "The path is blocked by debris! You'll need to move and turn repeatedly.",
    instruction: "Use a loop to repeat a move and a turn pattern 3 times.",
    concepts: ["Patterns", "Loops"],
    startPos: { x: 1, y: 6 },
    goalPos: { x: 4, y: 3 },
    initialCode: "for i in range(3):\n  robot.move_forward()\n  robot.turn_right()\n  robot.move_forward()\n  robot.turn_left()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 6,
    title: "The Scanner",
    description: "Byte has a new sensor! It can detect if a wall is directly in front of it.",
    instruction: "Use `if robot.is_wall_ahead():` to turn only when needed. Move 5 times.",
    concepts: ["If Statements", "Sensors"],
    startPos: { x: 1, y: 4 },
    goalPos: { x: 6, y: 4 },
    initialCode: "for i in range(5):\n  if robot.is_wall_ahead():\n    robot.turn_left()\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 7,
    title: "Nested Navigation",
    description: "To reach the far sector, we need a loop within a loop!",
    instruction: "Use a nested loop. A square is 4 sides, repeat that pattern 2 times.",
    concepts: ["Nested Loops", "Complexity"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 5, y: 1 },
    initialCode: "for i in range(2):\n  for j in range(4):\n    robot.move_forward()\n    robot.turn_right()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 8,
    title: "The Great Detour",
    description: "A huge canyon blocks the direct route. You'll need to combine variables and if-logic.",
    instruction: "Use a variable for distance and an `if` statement to check for walls.",
    concepts: ["Logic", "Combined Skills"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 1, y: 5 },
    initialCode: "dist = 4\nfor i in range(dist):\n  if robot.is_wall_ahead():\n    robot.turn_left()\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 9,
    title: "Crystal Labyrinth",
    description: "The crystals interfere with our sensors. You'll need a precise loop of 8 steps.",
    instruction: "The goal is hidden behind a double-corner. Use loops and variables together.",
    concepts: ["Optimization", "Precision"],
    startPos: { x: 0, y: 0 },
    goalPos: { x: 2, y: 2 },
    initialCode: "for i in range(2):\n  robot.move_forward()\n  robot.move_forward()\n  robot.turn_right()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 10,
    title: "Galactic Mastery",
    description: "The final test! Reach the heart of the galaxy station using a loop and if-checks.",
    instruction: "Navigate the complex corridor. Move 10 times and check for walls at every step.",
    concepts: ["Mastery", "Final Exam"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 4, y: 4 },
    initialCode: "for i in range(12):\n  if robot.is_wall_ahead():\n    robot.turn_right()\n  robot.move_forward()",
    grid: [
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.GOAL, TileType.WALL, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 11,
    title: "The Staircase",
    description: "A diagonal path lies ahead. Zig-zag your way to the top!",
    instruction: "Climb the stairs! Use a loop to repeat the 'up and right' movement.",
    concepts: ["Zig-Zag", "Patterns"],
    startPos: { x: 1, y: 6 },
    goalPos: { x: 5, y: 2 },
    initialCode: "for i in range(4):\n  robot.move_forward()\n  robot.turn_left()\n  robot.move_forward()\n  robot.turn_right()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 12,
    title: "The Box",
    description: "Patrol the perimeter of the containment unit.",
    instruction: "Walk around the square. 4 sides, 4 moves each.",
    concepts: ["Square Path", "Loops"],
    startPos: { x: 2, y: 5 },
    goalPos: { x: 2, y: 5 }, // Returns to start!
    initialCode: "for i in range(4):\n  for j in range(3):\n    robot.move_forward()\n  robot.turn_left()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 13,
    title: "Backtrack",
    description: "Dead end? No, it's a retrieval mission. Go in, then come back out.",
    instruction: "Go forward 3 steps, turn around (2 turns), then go back 3 steps.",
    concepts: ["Reversing", "Functions"],
    startPos: { x: 1, y: 3 },
    goalPos: { x: 0, y: 3 }, // Adjacent to start
    initialCode: "steps = 3\nfor i in range(steps):\n  robot.move_forward()\n\nrobot.turn_left()\nrobot.turn_left()\n\nfor i in range(steps):\n  robot.move_forward()",
    grid: [
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 14,
    title: "Slalom",
    description: "Weave through the pillars. Accuracy is key.",
    instruction: "Move, Turn Left, Move, Turn Right. Repeat to slalom.",
    concepts: ["Weaving", "Complex Patterns"],
    startPos: { x: 1, y: 6 },
    goalPos: { x: 5, y: 2 },
    initialCode: "for i in range(2):\n  robot.move_forward()\n  robot.turn_left()\n  robot.move_forward()\n  robot.turn_right()\n  robot.move_forward()\n  robot.turn_right()\n  robot.move_forward()\n  robot.turn_left()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 15,
    title: "The Fork",
    description: "A path splits. One way is blocked. Choose wisely... or let the code choose!",
    instruction: "Check if the left is clear. If so, turn left. Else, go right.",
    concepts: ["Decision Making", "Branches"],
    startPos: { x: 3, y: 6 },
    goalPos: { x: 1, y: 2 },
    initialCode: "robot.move_forward()\nif robot.is_wall_ahead():\n  robot.turn_right()\nelse:\n  robot.turn_left()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY], // Two goals? No, just one target.
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 16,
    title: "Obstacle Course",
    description: "Debris scattered everywhere. Move carefully.",
    instruction: "Move 6 times. If you feel a wall, dodge it!",
    concepts: ["Reactive", "Sensor"],
    startPos: { x: 0, y: 4 },
    goalPos: { x: 7, y: 4 },
    initialCode: "for i in range(7):\n  if robot.is_wall_ahead():\n    robot.turn_left()\n    robot.move_forward()\n    robot.turn_right()\n    robot.move_forward()\n    robot.turn_right()\n    robot.move_forward()\n    robot.turn_left()\n  else:\n    robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.GOAL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 17,
    title: "The Search",
    description: "The goal is somewhere in this row... or the next.",
    instruction: "Scan rows. Go straight until you hit a wall, then turn.",
    concepts: ["Algorithms", "Searching"],
    startPos: { x: 1, y: 1 },
    goalPos: { x: 6, y: 2 },
    initialCode: "for i in range(3):\n  for j in range(5):\n     if robot.is_wall_ahead():\n       robot.turn_right()\n     else:\n       robot.move_forward()",
    grid: [
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL],
      [TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.WALL],
      [TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 18,
    title: "Long Haul",
    description: "A marathon run. Conserve your energy (and lines of code).",
    instruction: "Use a variable `x = 6` to travel the long distance.",
    concepts: ["Variables", "Efficiency"],
    startPos: { x: 1, y: 7 },
    goalPos: { x: 1, y: 1 },
    initialCode: "long_dist = 6\nshort_dist = 2\n\nfor i in range(long_dist):\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.GOAL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 19,
    title: "The Maze",
    description: "A classic labyrinth. Right-hand rule might work?",
    instruction: "Follow the path. It winds and turns.",
    concepts: ["Maze Solving", "Logic"],
    startPos: { x: 0, y: 7 },
    goalPos: { x: 4, y: 4 },
    initialCode: "for i in range(15):\n  if robot.is_wall_ahead():\n    robot.turn_left()\n  else:\n    robot.move_forward()\n    robot.turn_right()\n    if not robot.is_wall_ahead():\n       robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.GOAL, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  },
  {
    id: 20,
    title: "Omega Station",
    description: "The final frontier. Complex structures guard the core.",
    instruction: "Combine everything! Loops, checks, and variables.",
    concepts: ["Grand Finale", "All Skills"],
    startPos: { x: 1, y: 7 },
    goalPos: { x: 6, y: 0 },
    initialCode: "for i in range(10):\n  if robot.is_wall_ahead():\n    robot.turn_left()\n  robot.move_forward()",
    grid: [
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.GOAL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.EMPTY, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.WALL, TileType.EMPTY],
      [TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY, TileType.EMPTY],
    ]
  }
];
